namespace Sean.Utility.Enums
{
    #region NetworkConnection

    public enum ERROR_ID
    {
        /// <summary>
        /// Success
        /// </summary>
        NO_ERROR = 0,

        ERROR_ACCESS_DENIED = 5,
        ERROR_ACCOUNT_DISABLED = 1331,
        ERROR_ALREADY_ASSIGNED = 85,
        ERROR_BAD_DEV_TYPE = 66,
        ERROR_BAD_DEVICE = 1200,
        ERROR_BAD_NET_NAME = 67,
        ERROR_BAD_PROFILE = 1206,
        ERROR_BAD_PROVIDER = 1204,
        ERROR_BAD_USERNAME = 2202,
        ERROR_BUSY = 170,
        ERROR_CANCELLED = 1223,
        ERROR_CANNOT_OPEN_PROFILE = 1205,
        ERROR_DEVICE_ALREADY_REMEMBERED = 1202,
        ERROR_EXTENDED_ERROR = 1208,
        ERROR_INVALID_ADDRESS = 487,
        ERROR_INVALID_PARAMETER = 87,
        ERROR_INVALID_PASSWORD = 86,
        ERROR_LOGON_FAILURE = 1326,
        ERROR_NO_NET_OR_BAD_PATH = 1203,
        ERROR_NO_NETWORK = 1222,

        ERROR_DEVICE_IN_USE = 2404,
        ERROR_NOT_CONNECTED = 2250,
        ERROR_OPEN_FILES = 2401
    }

    internal enum RESOURCE_SCOPE
    {
        RESOURCE_CONNECTED = 1,
        RESOURCE_GLOBALNET = 2,
        RESOURCE_REMEMBERED = 3,
        RESOURCE_RECENT = 4,
        RESOURCE_CONTEXT = 5
    }

    internal enum RESOURCE_TYPE
    {
        RESOURCETYPE_ANY = 0,
        RESOURCETYPE_DISK = 1,
        RESOURCETYPE_PRINT = 2,
        RESOURCETYPE_RESERVED = 8,
    }

    internal enum RESOURCE_DISPLAYTYPE
    {
        RESOURCEDISPLAYTYPE_GENERIC = 0,
        RESOURCEDISPLAYTYPE_DOMAIN = 1,
        RESOURCEDISPLAYTYPE_SERVER = 2,
        RESOURCEDISPLAYTYPE_SHARE = 3,
        RESOURCEDISPLAYTYPE_FILE = 4,
        RESOURCEDISPLAYTYPE_GROUP = 5,
        RESOURCEDISPLAYTYPE_NETWORK = 6,
        RESOURCEDISPLAYTYPE_ROOT = 7,
        RESOURCEDISPLAYTYPE_SHAREADMIN = 8,
        RESOURCEDISPLAYTYPE_DIRECTORY = 9,
        RESOURCEDISPLAYTYPE_TREE = 10,
        RESOURCEDISPLAYTYPE_NDSCONTAINER = 11
    }

    internal enum RESOURCE_USAGE
    {
        RESOURCEUSAGE_CONNECTABLE = 1,
        RESOURCEUSAGE_CONTAINER = 2,
        RESOURCEUSAGE_NOLOCALDEVICE = 4,
        RESOURCEUSAGE_SIBLING = 8,
        RESOURCEUSAGE_ATTACHED = 16,
        RESOURCEUSAGE_ALL = (RESOURCEUSAGE_CONNECTABLE | RESOURCEUSAGE_CONTAINER | RESOURCEUSAGE_ATTACHED),
    }

    #endregion
}
